# goal
int32 LEFT_ARM=0
int32 RIGHT_ARM=1
int32 arm
float32 upperbound_x
float32 upperbound_y
float32 upperbound_angle
float32 cycle_time
geometry_msgs/PoseStamped goal_pose
std_msgs/Duration timeout
---
# result
float32 progress # in percent
---
# feedback
float32 progress # in percent